### ISSUE TITLE
Error installing marginalia.ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by venkateshan-niladri** [basecamp/marginalia#100] opened 2020-03-07 16:56 UTC
I am facing issues while installing marginalia-1.6.0. 
I am using ruby version 2.2.5 and rails 3.2.22.5.
when I run bundle install, the process gets failed at marginalia installation step. 

```
$ gem install marginalia -v '1.6.0'
Building native extensions.  This could take a while...
ERROR:  Error installing marginalia:
	ERROR: Failed to build gem native extension.

    /Users/veniladri/.rbenv/versions/2.2.5/bin/ruby mkrf_conf.rb

rake failed, exit code 1

Gem files will remain installed in /Users/veniladri/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/marginalia-1.6.0 for inspection.
Results logged to /Users/veniladri/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-19/2.2.0-static/marginalia-1.6.0/gem_make.out
```

Please suggest what can be going wrong?

Thanks,
Venky

**Comment by venkateshan-niladri** [comment] 2020-03-07 16:58
FYI, The same is working in case of version 1.7.0. But I have to use 1.6.0 as per project guidelines.

**Comment by bf4** [comment] 2020-09-15 20:00
duplicate of https://github.com/basecamp/marginalia/issues/107

**Comment by sj26** [comment] 2021-08-09 00:07
Please use a newer version of marginalia, the extension causing this failure was removed in #78.

**Closed by sj26** 2021-08-09 00:07 UTC
